### ISSUE TITLE
Make this repo a template

### ISSUE THREAD

**Issue by MatyiFKBT** [Groftware/template-reactnpm#1]
Hey!

I read your [dev.to article](https://dev.to/cjinghong/publishing-your-first-react-component-to-npm-7bb) about how to publish a React component to npm, and thought you could turn this repo to a template, so people can easily fork it and get started 

You can enable this setting in your repos settings:
![img](https://user-images.githubusercontent.com/6183867/92996315-fb21dd00-f50a-11ea-83ad-a157acb22d77.png)

Cheers!

**Comment by cjinghong** [comment]
@MatyiFKBT Great suggestion, thanks mate!
